### ISSUE TITLE
Indicator for the `x` mode

### ISSUE THREAD

**Issue by rawtaz** [robinovitch61/kl#2]
**Is your feature request related to a problem? Please describe.**
When having applied a filter and using the `x` key to toggle between showing only the matched lines and all lines, it is not clear to me in the GUI which of the "x modes" I am in.

**Describe the solution you'd like**
I would like some form of "flag" or other indicator shown in the GUI, by which I can always tell whether the effect of the `x` key is currently applied or not.

**Describe alternatives you've considered**
The only way currently to know whether the "x effect" is applied or not is to look look at the line count at the bottom left while toggling the mode using `x`, to determine when it is having an effect (less lines shown) and not (more lines shown).

**Additional context**
It might be debatable, but I do see some resemblance to this fine gentleman:

![image](https://github.com/user-attachments/assets/e2552513-e752-4864-b737-eb0aac9c37a2)

**Comment by robinovitch61** [comment]
Hey @rawtaz , thanks for the idea - I think it's a good one. If you hit "p" to pause logs, you'll see an indicator I added in the header to show that logs are paused. We could add a similar indicator, maybe "matches", next to "paused"

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/8cdcf913-2ee1-4683-9648-7e9541067cf9">

If you'd like, feel free to open a pull request adding this functionality. Otherwise, I'll get to it ASAP.

**Comment by rawtaz** [comment]
I agree, that sounds like a perfect solution :) If you don't mind implementing it, I think that would be the quickest by far.

**Comment by robinovitch61** [comment]
I ended up going a slightly different route - the filter will read `(matches only)` when context is off, and either `(#/#, n/N to cycle)` or `(no matches)` when context is shown. Released in v0.5.0
